[project]
name = "playwright-py"
version = "0.1.1"
description = "Automated tests with python and pom."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faker>=40.1.0",
    "openpyxl>=3.1.5",
    "pytest-playwright>=0.7.2",
]
